site_name: "Kirchenanh채nger"
site_url: https://example.com
site_description: "Benutzerhandbuch f체r den Kirchenanh채nger der Evangelisch-Reformierten Kirchengemeinde Neunkirchen"
copyright: "Ev.-Ref. Kirchengemeinde Neunkirchen"
theme: readthedocs
markdown_extensions:
  - admonition
plugins:
  - search
  - print-site:
      toc_title: 'Inhaltsverzeichnis'
      print_page_title: 'Druckansicht'
      add_cover_page: true
      cover_page_template: 'docs/assets/templates/cover_page.tpl'
nav:
  - index.md
  - 체bernahme.md
  - aufbau.md
  - stromversorgung.md
  - stromerzeuger.md
  - tontechnik.md
  - network.md
